services:
  singstar-db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - singstar-web-db:/var/lib/mysql
    restart: unless-stopped
    environment:
      TZ: UTC+1
      MYSQL_ROOT_PASSWORD: SecurePassword!
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: EvenMoreSecurePassword!
  singstar-web:
    image: ghcr.io/singularity-game/singularity:master
    environment:
      APP_URL: <app-url>
      AUTHENTICATION_JWT_SECRET: <secret>
      DB_HOST: "singstar-db"
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: SecurePassword!
      DB_DATABASE: db
      SMTP_SECURE: 'true'
      SMTP_HOST: <SMTP-HOST>
      SMTP_USERNAME: <SMTP-USER>
      SMTP_PASSWORD: <SMTP-PASSWORD>
      SMTP_FROM: <SMTP-FROM>
      SONG_DIRECTORY: songs
    volumes:
      - singstar-web-songs:/usr/src/app/songs
    ports:
      - 3333:80

volumes:
  singstar-web-db:
  singstar-web-songs:
