services:
  singularity-db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - singularity-db:/var/lib/mysql
    restart: unless-stopped
    environment:
      TZ: UTC+1
      MYSQL_ROOT_PASSWORD: SecurePassword!
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: EvenMoreSecurePassword!
  singularity:
    image: ghcr.io/singularity-game/singularity:main
    environment:
      APP_URL: http://localhost
      AUTHENTICATION_JWT_SECRET: syfnhiasjfpkf0端pfl端paslf端poaslfa端sfafasfd
      DB_HOST: singularity-db
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: EvenMoreSecurePassword!
      DB_DATABASE: db
      SMTP_SECURE: 'true'
      SMTP_HOST: <SMTP-HOST>
      SMTP_USERNAME: <SMTP-USER>
      SMTP_PASSWORD: <SMTP-PASSWORD>
      SMTP_FROM: <SMTP-FROM>
      SONG_DIRECTORY: songs
      ENABLE_YOUTUBE: false
      ENABLE_AUTO_INDEXING: true
    volumes:
      - singularity-songs:/usr/src/app/songs
    ports:
      - 3333:3333

volumes:
  singularity-db:
  singularity-songs:
